// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { Navbar } from "../components/Navbar";
// import { Toaster } from "../components/ui/sonner";
// import { AppSidebar } from "../components/app-sidebar";
// import { SidebarProvider } from "@/components/ui/sidebar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <Navbar />
//          <div className="min-h-screen bg-gray-50">
//           {children}
//          </div>

//          <Toaster />
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { Toaster } from "@/components/ui/sonner";
// 1. นำเข้า MobileFloatingMenu (อย่าลืมสร้างไฟล์นี้ไว้ในโฟลเดอร์ components นะครับ)
import MobileFloatingMenu from "@/components/MobileFloatingMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  // แนะนำ: คุณอาจจะอยากเปลี่ยน Title ตรงนี้เป็น "Foundit." ให้ตรงกับแบรนด์
  title: "Foundit. | ศูนย์กลางแจ้งของหาย", 
  description: "ระบบที่จะช่วยคุณตามหาสิ่งของที่หาย และประกาศตามหาเจ้าของ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#FAFAFA]`}
      >
        <Navbar />
        
        {/* 2. ปรับลด pb-24 เหลือแค่ pb-16 ก็พอครับ เพราะปุ่มลอย (Floating Button) 
            ไม่ได้กินพื้นที่ด้านล่างเป็นแนวยาวเหมือน BottomNav */}
        <div className='min-h-screen pb-16 lg:pb-0'>{children}</div>

        {/* 3. วางปุ่ม Mobile Floating Menu ไว้ตรงนี้ (มันจะแสดงแค่บนมือถือเพราะเราตั้งคลาส lg:hidden ไว้ในตัวมันแล้ว) */}
        <MobileFloatingMenu />
        
        <Toaster />
      </body>
    </html>
  );
}
