// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { Navbar } from "../components/Navbar";
// import { Toaster } from "../components/ui/sonner";
// import { AppSidebar } from "../components/app-sidebar";
// import { SidebarProvider } from "@/components/ui/sidebar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <Navbar />
//          <div className="min-h-screen bg-gray-50">
//           {children}
//          </div>

//          <Toaster />
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// แนะนำให้ทำการ Export Navbar และ BottomNav ออกมาจากไฟล์ components/Navbar.tsx ที่เราสร้างกันไปก่อนหน้านี้
import { Navbar } from "@/components/Navbar";
import { Toaster } from "@/components/ui/sonner";
import { BottomNav } from "@/components/BottomNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CU Lost & Found",
  description: "ศูนย์กลางแจ้งของหายและของที่พบ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#FAFAFA]`}
      >
        <Navbar />
        {/* เพิ่ม pb-20 (padding-bottom) ในหน้าจอเล็ก และเอาออก (lg:pb-0) ในหน้าจอใหญ่ เพื่อไม่ให้ Mobile Bottom Nav บังเนื้อหาข้างล่าง */}
        <div className='min-h-screen pb-24 lg:pb-0'>{children}</div>

        {/* เมนูด้านล่างสำหรับมือถือ */}
        {/* <BottomNav /> */}
        <Toaster />
      </body>
    </html>
  );
}
